coverage:
  precision: 2
  round: down
  range: "70...90"

  status:
    project:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  
ignore:
  - "app/dal/**"
  - "app/service/**"
  - "app/util/**"
  - "app/Program.cs"